theons_list/urls.py
from django.conf.urls import url
from django.contrib import admin
from theons_list import settings
from theonsapp.views import IndexView, UserCreateView, CategoryDetailView, \
                            SubCategoryItemView, ItemDetailView, \
                            MakeListingView, ListCategoryAPIView, \
                            ListSubCategoryAPIView, \
                            ListPostSubCategoryAPIView, \
                            ListPostCategoryAPIView, \
                            DetailPostAPIView, CreatePostAPIView, \
                            RetrieveCategoryAPIView, \
                            RetrieveSubCategoryAPIView, UserCreateAPIView, \
                            ListOfAPIViews, AboutView
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^accounts/login/', auth_views.login, name='login'),
    url(r'^logout/', auth_views.logout_then_login, name='logout'),
    url(r'^signup/', UserCreateView.as_view(), name='signup'),
    url(r'^about/$', AboutView.as_view(), name='about'),
    url(
        r'^media/(?P<path>.*)',
        "django.views.static.serve",
        {"document_root": settings.MEDIA_ROOT}
        ),
    url(
        r'^category/(?P<pk>\d+)',
        CategoryDetailView.as_view(),
        name="category_detail"
        ),
    url(
        r'^subcategory/(?P<pk>\d+)/(?P<ordering>\d)',
        SubCategoryItemView.as_view(),
        name='sub_item_list'
        ),
    url(
        r'^item_detail/(?P<pk>\d+)',
        ItemDetailView.as_view(),
        name='item_detail'
        ),
    url(
        r'^create_listing/(?P<pk>\d+)',
        MakeListingView.as_view(),
        name='create_listing'
        ),
    url(r'^listapi/$', ListOfAPIViews.as_view(), name='list_of_apis'),

    # Begin API views
    url(
        r'^api/categories/',
        ListCategoryAPIView.as_view(),
        name='category_api_view'
        ),
    url(
        r'^api/subcategories/',
        ListSubCategoryAPIView.as_view(),
        name='subcategory_api_view'
        ),
    url(
        r'^api/subcategory/(?P<pk>\d+)/posts/',
        ListPostSubCategoryAPIView.as_view(),
        name='post_by_subcategory_api_view'
        ),
    url(
        r'^api/category/(?P<pk>\d+)/posts/',
        ListPostCategoryAPIView.as_view(),
        name='post_by_category_api_view'
        ),
    url(
        r'^api/post/(?P<pk>\d+)',
        DetailPostAPIView.as_view(),
        name='post_api_view'
        ),
    url(
        r'^api/post/create/',
        CreatePostAPIView.as_view(),
        name='post_api_view'
        ),
    url(
        r'^api/category/(?P<pk>\d+)/details/',
        RetrieveCategoryAPIView.as_view(),
        name='retrieve_category_api_view'
        ),
    url(
        r'^api/subcategory/(?P<pk>\d+)/details/',
        RetrieveSubCategoryAPIView.as_view(),
        name='retrieve_subcategory_api_view'
        ),
    url(r'^api/user/', UserCreateAPIView.as_view(), name='user_create_view')


    ]

theonsapp/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token


class City(models.Model):
    city_name = models.CharField(max_length=50)

    def __str__(self):
        return self.city_name


class Category(models.Model):
    name = models.CharField(max_length=50)
    photo = models.ImageField(upload_to='uploads/categories',
                              default='uploads/default.jpg'
                              )
    description = models.CharField(
                                   max_length=255,
                                   blank=True,
                                   null=True,
                                   default='No Description'
                                   )

    def __str__(self):
        return self.name


class SubCategory(models.Model):
    name = models.CharField(max_length=50)
    category = models.ForeignKey(Category)
    photo = models.ImageField(upload_to='uploads/subcategories',
                              default='uploads/default.jpg'
                              )
    description = models.CharField(
                                   max_length=255,
                                   blank=True,
                                   null=True,
                                   default='No Description'
                                   )

    def __str__(self):
        return self.name


class UserProfile(models.Model):
    user = models.OneToOneField("auth.User")
    home_city = models.ForeignKey(City, null=True)

    def __str__(self):
        return self.user.username


class Item(models.Model):
    location = models.ForeignKey(City)
    seller = models.ForeignKey("auth.User", related_name="item_for_sale")
    name = models.CharField(max_length=100)
    full_description = models.TextField()
    time_listed = models.DateTimeField(auto_now_add=True)
    photo = models.ImageField(upload_to='uploads',
                              default='uploads/default.jpg')
    price = models.IntegerField()
    subcategory = models.ForeignKey(SubCategory)

    def __str__(self):
        return self.name


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)

theonsapp/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from theonsapp.models import City


class NewUserCreation(UserCreationForm):
    home_city = forms.ModelChoiceField(queryset=City.objects.all())

theonsapp/views.py
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.views.generic import CreateView, ListView, DetailView, TemplateView
from rest_framework.generics import ListAPIView, RetrieveUpdateDestroyAPIView,\
     CreateAPIView, RetrieveAPIView
from theonsapp.forms import NewUserCreation
from theonsapp.models import Item, SubCategory, Category, City, UserProfile
from theonsapp.permissions import IsOwnerOrReadOnly
from theonsapp.serializers import CategorySerializer, SubCategorySerializer, \
    PostSerializer, UserSerializer
from rest_framework.permissions import IsAuthenticated, \
    IsAuthenticatedOrReadOnly


class IndexView(ListView):
    template_name = 'index.html'
    model = Category


class AboutView(TemplateView):
    template_name = 'about.html'


class UserCreateView(CreateView):
    model = User
    form_class = NewUserCreation

    def form_valid(self, form):
        user_object = form.save()
        city = form.cleaned_data.get("home_city")
        profile = UserProfile.objects.create(user=user_object, home_city=city)
        profile.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('login')


class MakeListingView(CreateView):
    model = Item
    fields = ['name', 'full_description', 'photo', 'price']

    def form_valid(self, form):
        post = form.save(commit=False)
        post.subcategory = SubCategory.objects.get(pk=self.kwargs.get('pk'))

        user_profile = UserProfile.objects.get(user=self.request.user)
        post.location = City.objects.get(pk=user_profile.home_city.pk)
        post.seller_id = user_profile.user.pk
        post.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pk = self.kwargs.get('pk')
        context['subcategory'] = SubCategory.objects.get(pk=pk)
        return context

    def get_success_url(self):
        return reverse('index')


class CategoryDetailView(DetailView):
    model = Category

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pk = self.kwargs.get('pk')
        context['category'] = Category.objects.get(pk=pk)
        return context


class SubCategoryItemView(ListView):
    model = Item

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        sub = self.kwargs.get('pk')
        context['subcategory'] = SubCategory.objects.get(pk=sub)
        if self.kwargs.get('ordering') == '1':
            item_list = Item.objects.filter(
                                            subcategory_id=sub
                                            ).order_by("-time_listed")
        elif self.kwargs.get('ordering') == '2':
            item_list = Item.objects.filter(
                                            subcategory_id=sub
                                            ).order_by("-price")
        elif self.kwargs.get('ordering') == '3':
            item_list = Item.objects.filter(
                                            subcategory_id=sub
                                            ).order_by("price")
        context['item_list'] = item_list
        return context


class ItemDetailView(DetailView):
    model = Item


class ListOfAPIViews(TemplateView):
    template_name = 'api_list.html'


class ListCategoryAPIView(ListAPIView):
    serializer_class = CategorySerializer
    queryset = Category.objects.all()


class ListSubCategoryAPIView(ListAPIView):
    serializer_class = SubCategorySerializer
    queryset = SubCategory.objects.all()


class ListPostSubCategoryAPIView(ListAPIView):
    serializer_class = PostSerializer

    def get_queryset(self):
        captured_pk = self.kwargs['pk']
        return Item.objects.filter(subcategory_id=captured_pk)


class ListPostCategoryAPIView(ListAPIView):
    serializer_class = PostSerializer

    def get_queryset(self):
        captured_pk = self.kwargs['pk']
        return Item.objects.filter(subcategory__category_id=captured_pk)


class DetailPostAPIView(RetrieveUpdateDestroyAPIView):
    serializer_class = PostSerializer
    permission_classes = (IsAuthenticatedOrReadOnly,
                          IsOwnerOrReadOnly,
                          )
    queryset = Item.objects.all()


class CreatePostAPIView(CreateAPIView):
    serializer_class = PostSerializer
    queryset = Item.objects.all()
    permission_classes = (IsAuthenticated,)


class RetrieveCategoryAPIView(RetrieveAPIView):
    serializer_class = CategorySerializer
    queryset = Category.objects.all()


class RetrieveSubCategoryAPIView(RetrieveAPIView):
    serializer_class = CategorySerializer
    queryset = SubCategory.objects.all()


class UserCreateAPIView(CreateAPIView):
    serializer_class = UserSerializer

theonsapp/templates/about.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
{% include 'index_navbar_include.html' %}
<header style="margin: 2%;">
  <h4 class="roboto-font">Hello!</h4>
</header>
<main>
  <p class="roboto-font">
  About this site,
  </p>
  <p class="roboto-font">
    Theon's List started out as a weekend assignment for week six of my cohort at The Iron Yard in Greenville.
    The assignment was to build a clone of Craigslist replicating the ability of the user to list items, upload images and allow
    sorting of listed items by price and date listed.
  </p>
  <p class="roboto-font">
    Later in the cohort I revisited this assignment to add API functionality using the Django REST Framework. Most recently,
    I picked this as one of my favorite sites that I have built and decided to expand on it with a much nicer interface and
    some fun styling using Materialize CSS. If you have any questions feel free to drop me a line. You can get in touch
    with me at jude.nowicki@gmail.com or visit my personal home page at <a href="http://judenowicki.com">judenowicki.com</a>.
  </p>
</main>
{% endblock %}

{% block footer %}
{% include 'footer_include.html' %}
{% endblock %}

theonsapp/templates/api_list.html
{% extends 'base.html' %}
{% block content %}
{% include 'index_navbar_include.html' %}
<header></header>
<main>
  <h4>Theon's List API Access Points</h4>
  <div class="collection">
    <a href="{% url 'category_api_view' %}" class="collection-item">api/categories/</a>
    <a href="{% url 'subcategory_api_view' %}" class="collection-item">api/subcategories/</a>
    <a href="{% url 'user_create_view' %}" class="collection-item">api/user/</a>
    <a href="{% url 'post_api_view' %}" class="collection-item">api/post/create/</a>
  </div>
  <br>
  <h4>API Access Points Requiring Primary Key</h4>
  <ul class="collection">
    <li class="collection-item">api/subcategory/(pk)/posts/</li>
    <li class="collection-item">api/category/(pk)/posts/</li>
    <li class="collection-item">api/post/(pk)</li>
    <li class="collection-item">api/category/(pk)/details/</li>
    <li class="collection-item">api/subcategory/(pk)/details/</li>
  </ul>
</main>
{% endblock %}

{% block footer %}
{% include 'footer_include.html' %}
{% endblock %}

theonsapp/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link href='https://fonts.googleapis.com/css?family=MedievalSharp' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="{% static 'css/custom.css' %}" title="no title" charset="utf-8" type='text/css'>
    <meta charset="UTF-8">
    <title>Theon's List</title>
</head>
<body>

{% block navbar %}
{% endblock %}

{% block content %}
{% endblock %}

{% block footer %}
{% endblock %}
<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>
</body>
</html>

theonsapp/templates/base_form.html
<div class="row">
    <div class="col s12 m8 l6">
        <div class="card-panel">
            <span class="default">
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <br>
                    <button class="btn waves-effect waves-default grey" type="submit" name="action">Submit</button>
                </form>
            </span>
        </div>
    </div>
</div>

theonsapp/templates/breadcrumb_navbar_include.html
<nav>
    <div class="nav-wrapper brown darken-4 z-depth-1">
      <div class="col s12" style="margin: 2%">
        <a href="{% url 'index' %}" class="breadcrumb">Home</a>
        <a href="{% url 'category_detail' subcategory.category.pk %}" class="breadcrumb">{{ subcategory.category }}</a>
        <a href="{% url 'sub_item_list' subcategory.pk 1 %}" class="breadcrumb">{{ subcategory }}</a>
        <a href="{% url 'index' %}" class="brand-logo right">Theon's List</a>

      </div>
    </div>
  </nav>

theonsapp/templates/category_breadcrumb_navbar_include.html
<nav class="brown darken-4">
  <div class="nav-wrapper z-depth-3">
    <a href="{% url 'index' %}" class="breadcrumb" style="margin-left: 2%;">Home</a>
    <a href="{% url 'category_detail' category.pk %}" class="breadcrumb">{{ category }}</a>
    <a href="{% url 'index' %}" class="brand-logo right" style="margin-right: 2%;">Theon's List</a>
  </div>
</nav>

theonsapp/templates/footer_include.html
<footer class="page-footer z-depth-4 brown darken-4">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Theon's List</h5>
        <p class="grey-text text-lighten-4">A Medieval Themed Site Listing Items For Sale</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">My Other Sites</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!"></a></li>
          <li><a class="grey-text text-lighten-3" href="http://judenowicki.com">Portfolio</a></li>
          <li><a class="grey-text text-lighten-3" href="http://serverbuddy.judenowicki.com">Server Buddy</a></li>
          <li><a class="grey-text text-lighten-3" href="#!"></a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    © 2016 judenowicki.com
    <a class="grey-text text-lighten-4 right" href="{% url 'about' %}">About</a>
    </div>
  </div>
</footer>

theonsapp/templates/index.html
{% extends 'base.html' %}

{% block navbar %}
{% include 'index_navbar_include.html' %}
{% endblock navbar %}

{% block content %}
<header>
    <div class="col s8 m8 center">
      <div class="card-panel grey">
        <span class="white-text" style="font-size: 16pt;">Welcome to Theon's List, a medieval themed site listing items for sale.
          <br>Log in, then navigate to a Subcategory to place your own listing.
        </span>
      </div>
    </div>
</header>
<main>
  <div class="col l12">
    <h2>Categories</h2>
    <div class="row">
      {% for category in object_list %}
          <div class="col s12 m6 l2">
            <div class="card z-depth-4">
              <div class="card-image waves-effect waves-block waves-light">
                <img class="activator" src="{{ category.photo.url }}">
                <span class="card-title">{{ category }}</span>
              </div>
              <div class="card-content">
                <span class="card-title activator grey-text text-darken-4">{{ category.description }}<i class="material-icons right">more_vert</i></span>
                <p><a href="{% url 'category_detail' category.pk %}">Explore</a></p>
              </div>
              <div class="card-reveal">
                <span class="card-title grey-text text-darken-4">Subcategories<i class="material-icons right">close</i></span>
                {% for sub in category.subcategory_set.all %}
                <li><a href="{% url 'sub_item_list' sub.pk 1 %}">{{ sub }}</a></li>
                {% endfor %}
              </div>
            </div>
          </div>
      {% endfor %}
    </div>
  </div>
</main>

{% endblock content %}

{% block footer %}
{% include 'footer_include.html' %}
{% endblock footer %}

theonsapp/templates/index_navbar_include.html
<nav class="brown darken-4">
    <div class="nav-wrapper z-depth-3">
      <div class="col s12">
        <a href="{% url 'index' %}" class="brand-logo left" style="margin-left: 2%;">Theon's List</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><a href="{% url 'list_of_apis' %}">API List</a></li>
          {% if user.is_authenticated %}
          <li><a href="{% url 'logout' %}">Log Out</a></li>
          {% else %}
          <li><a href="{% url 'login' %}">Log In</a></li>
          <li><a href="{% url 'signup' %}">Sign Up</a></li>
          {% endif %}
          <li><a href="{% url 'about' %}">About</a></li>
        </ul>
      </div>
    </div>
  </nav>

theonsapp/templates/subcategory_breadcrumb_navbar_include.html
<nav class="brown darken-4">
  <div class="nav-wrapper z-depth-3">
    <a href="{% url 'index' %}" class="breadcrumb" style="margin-left: 2%;"> Home</a>
    <a href="{% url 'category_detail' subcategory.category.pk %}" class="breadcrumb">{{ subcategory.category }}</a>
    <a href="{% url 'sub_item_list' subcategory.pk 1 %}" class="breadcrumb">{{ subcategory }}</a>
    <a href="{% url 'index' %}" class="brand-logo right" style="margin-right: 2%;">Theon's List</a>
  </div>
</nav>